import Link from "next/link";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Blog — ZoikoLogia",
  description: "Perspective on governed AI accounting intelligence.",
};

export default function BlogPage() {
  return (
    <div className="min-h-screen bg-[#F9F7F1] text-[#16233d]">
      {/* ─── Hero Section (Full Width Border) ──────────────────────────────────── */}
      <div className="border-b border-[#e3d9c2]">
        <div className="mx-auto max-w-[1050px] px-6 pt-20 pb-16 md:pt-24 md:pb-20">
          <p className="mb-5 text-[11px] font-bold tracking-[0.15em] uppercase text-[#d97f0e]">
            — BLOG
          </p>
          <h1 className="mb-6 font-serif text-4xl md:text-[46px] font-medium leading-[1.15] text-[#071a33] whitespace-nowrap">
            Perspective on governed AI accounting intelligence.
          </h1>
          <p className="mb-10 max-w-3xl text-[17px] leading-relaxed text-[#5c6672]">
            Shorter reads on the thinking behind the platform — for the moments a full guide is more<br />
            than you need.
          </p>
          <div className="flex flex-wrap gap-3">
            <button className="rounded-full border border-[#e3d9c2] bg-white px-5 py-2.5 text-[13.5px] font-semibold text-[#123055] shadow-sm transition-all hover:bg-slate-50">
              Governance First
            </button>
            <button className="rounded-full border border-[#e3d9c2] bg-white px-5 py-2.5 text-[13.5px] font-semibold text-[#123055] shadow-sm transition-all hover:bg-slate-50">
              What &quot;Source-Backed&quot; Means
            </button>
            <button className="rounded-full border border-[#e3d9c2] bg-white px-5 py-2.5 text-[13.5px] font-semibold text-[#123055] shadow-sm transition-all hover:bg-slate-50">
              Chatbot vs. Advisor
            </button>
          </div>
        </div>
      </div>

      {/* ─── Page Content ──────────────────────────────────────────────────────── */}
      <div className="mx-auto max-w-[1050px] px-6 py-16 md:py-20">
        {/* ─── Blog Posts List ───────────────────────────────────────────────────── */}
        <div className="space-y-16 max-w-3xl">
          {/* Post 1 */}
          <article className="border-b border-[#e3d9c2] pb-16">
            <div className="mb-3 text-[13px] text-[#8b93a0]">6 min read</div>
            <h2 className="mb-5 font-serif text-[28px] font-medium leading-tight text-[#071a33]">
              Why Governance Has to Come Before Capability
            </h2>
            <div className="space-y-5 text-[16px] leading-[1.7] text-[#123055]">
              <p>
                Most AI products are built the same way: get the model working, ship it, add guardrails when<br />
                something goes wrong. That order works reasonably well for a writing assistant. It does not work for a<br />
                system that a professional might cite in a workpaper.
              </p>
              <p>
                The uncomfortable truth is that capability and governance pull in opposite directions early on. A model<br />
                unconstrained by source requirements will sound more fluent, more confident, and more &quot;helpful&quot; than<br />
                one that&apos;s been taught to say &quot;I don&apos;t have a sufficient source for that.&quot; Buyers evaluating on fluency<br />
                alone will often prefer the ungoverned version — right up until it costs them.
              </p>
              <p>
                Building governance in from the start means accepting a rougher, more qualified-sounding product in<br />
                exchange for one whose qualifications are actually true. That&apos;s the trade we made, and it&apos;s the reason<br />
                the platform exists at all.
              </p>
            </div>
          </article>

          {/* Post 2 */}
          <article className="border-b border-[#e3d9c2] pb-16">
            <div className="mb-3 text-[13px] text-[#8b93a0]">4 min read</div>
            <h2 className="mb-5 font-serif text-[28px] font-medium leading-tight text-[#071a33]">
              What &quot;Source-Backed&quot; Actually Means (and Doesn&apos;t)
            </h2>
            <div className="space-y-5 text-[16px] leading-[1.7] text-[#123055]">
              <p>
                &quot;Source-backed&quot; gets used loosely enough in AI marketing that it&apos;s worth being precise about it. It<br />
                does not mean an answer that happens to be correct. It does not mean an answer with a citation<br />
                appended after the fact, generated by a second pass that&apos;s just as capable of hallucinating a citation<br />
                as the first pass was of hallucinating an answer.
              </p>
              <p>
                It means the source was identified, versioned, and license-checked before generation — and that the<br />
                resulting answer can point back to a specific bundle, not just a vague sense that &quot;sources were<br />
                probably involved somewhere.&quot; If you can&apos;t trace an answer back to a specific, versioned source, it<br />
                isn&apos;t source-backed. It&apos;s source-adjacent.
              </p>
            </div>
          </article>

          {/* Post 3 */}
          <article className="pb-16">
            <div className="mb-3 text-[13px] text-[#8b93a0]">5 min read</div>
            <h2 className="mb-5 font-serif text-[28px] font-medium leading-tight text-[#071a33]">
              The Difference Between a Chatbot and an Advisor
            </h2>
            <div className="space-y-5 text-[16px] leading-[1.7] text-[#123055]">
              <p>
                A chatbot answers the question you asked. An advisor sometimes tells you that you asked the wrong<br />
                question, or that it doesn&apos;t have enough information to answer responsibly, or that this particular<br />
                matter needs a human with a license.
              </p>
              <p>
                That&apos;s a harder product to build, because &quot;no&quot; and &quot;not yet&quot; are legitimate, valuable outputs — and<br />
                most AI evaluation frameworks are built to reward confident answers, not appropriately withheld ones.<br />
                Professional-boundary design means treating a well-placed refusal as a feature shipped correctly, not<br />
                a failure to route around.
              </p>
            </div>
          </article>
        </div>

        {/* ─── Bottom CTA Card ───────────────────────────────────────────────────── */}
        <div className="relative mt-20 overflow-hidden rounded-[24px] bg-[#0A1628] p-12 text-center md:p-16 shadow-2xl">
          {/* Subtle gradient glow */}
          <div className="pointer-events-none absolute inset-0 bg-gradient-to-br from-[#0d9488]/10 via-transparent to-transparent opacity-80" />
          
          <div className="relative z-10 mx-auto max-w-2xl">
            <p className="mb-4 text-[11px] font-bold tracking-[0.15em] uppercase text-[#049783]">
              — WANT THE LONGER VERSION?
            </p>
            <h3 className="mb-10 font-serif text-[32px] md:text-[36px] font-medium leading-tight text-white">
              Guides go deeper than blog posts.
            </h3>
            <div className="flex flex-col items-center justify-center gap-4 sm:flex-row">
              <Link
                href="/guides"
                className="w-full sm:w-auto rounded-lg px-7 py-3.5 text-[14.5px] font-semibold text-white shadow-sm transition-all hover:opacity-95"
                style={{ backgroundColor: "#e59819" }}
              >
                Read the Guides
              </Link>
              <Link
                href="/resource"
                className="w-full sm:w-auto rounded-lg border border-[#2b3a50] bg-transparent px-7 py-3.5 text-[14.5px] font-semibold text-white transition-colors hover:bg-white/5"
              >
                Back to Resources
              </Link>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
